services:
  shiva:
    image: ghcr.io/adjuntor/shiva/shiva:latest
    container_name: shiva
    network_mode: bridge
    restart: unless-stopped
    volumes:
        - <volume-name>:/usr/src/app/config
